import sys
import os
import logging
import smtplib
import ssl
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import date
from dotenv import load_dotenv

# --- System Setup ---
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../")))
load_dotenv()

# --- App Imports ---
from app.database.connection import SessionLocal
from app.database.models import DailyDigest

# --- Configuration ---
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

# --- CSS Styling for the Email ---
# This makes the markdown look like a professional newsletter
EMAIL_CSS = """
<style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    h1 { color: #2c3e50; border-bottom: 2px solid #eaeaea; padding-bottom: 10px; }
    h2 { color: #34495e; margin-top: 25px; }
    a { color: #3498db; text-decoration: none; }
    a:hover { text-decoration: underline; }
    ul { padding-left: 20px; }
    li { margin-bottom: 8px; }
    blockquote { border-left: 4px solid #dfe6e9; padding-left: 15px; color: #7f8c8d; margin: 0; }
    code { background-color: #f8f9fa; padding: 2px 5px; border-radius: 3px; font-family: monospace; }
    .footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eaeaea; padding-top: 20px; }
</style>
"""

class EmailAgent:
    def __init__(self):
        self.db = SessionLocal()
        
        # Load Config
        self.sender_email = os.getenv("EMAIL_SENDER")
        self.password = os.getenv("EMAIL_PASSWORD")
        self.recipient_email = os.getenv("EMAIL_RECIPIENT")
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", 465))

    def get_latest_digest(self):
        """Fetches the most recent Daily Digest."""
        return self.db.query(DailyDigest).order_by(DailyDigest.date.desc()).first()

    def send_email(self, digest_obj):
        if not self.sender_email or not self.password:
            logger.error("❌ Email credentials missing in .env")
            return

        try:
            # 1. Convert Markdown to HTML
            html_content = markdown.markdown(digest_obj.content)
            
            # 2. Wrap in Full HTML Structure with CSS
            final_html = f"""
            <html>
            <head>{EMAIL_CSS}</head>
            <body>
                <h1>{digest_obj.title}</h1>
                <p><em>Date: {digest_obj.date}</em></p>
                <hr>
                {html_content}
                <div class="footer">
                    Generated by your Personal AI News Agent 🤖
                </div>
            </body>
            </html>
            """

            # 3. Create Message Object
            message = MIMEMultipart("alternative")
            message["Subject"] = f"AI Digest: {digest_obj.title}"
            message["From"] = self.sender_email
            message["To"] = self.recipient_email

            # Add HTML part
            part_html = MIMEText(final_html, "html")
            message.attach(part_html)

            # 4. Connect to SMTP Server (SSL)
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(self.smtp_server, self.smtp_port, context=context) as server:
                server.login(self.sender_email, self.password)
                server.sendmail(
                    self.sender_email, self.recipient_email, message.as_string()
                )

            print(f"✅ Email sent successfully to {self.recipient_email}")

        except Exception as e:
            logger.error(f"Failed to send email: {e}")

    def run(self):
        print("📧 Starting Email Agent...")
        
        # 1. Get Data
        latest_digest = self.get_latest_digest()
        
        if not latest_digest:
            print("⚠️ No digest found in database to send.")
            return

        # 2. Check if it's actually from today (Optional, but good practice)
        # If you want to force send whatever is latest, comment this out.
        if latest_digest.date != date.today():
             print(f"⚠️ Note: The latest digest is from {latest_digest.date}, not today.")
        
        print(f"🔹 Found Digest: '{latest_digest.title}'")
        
        # 3. Send
        self.send_email(latest_digest)

if __name__ == "__main__":
    EmailAgent().run()