import os
import sys
import smtplib
import ssl
import logging
from datetime import date
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
from sqlalchemy import func  # <-- Required for date comparison

# --- System Setup ---
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../")))
load_dotenv()

from app.database.connection import SessionLocal
from app.database.models import AggregatedSummary, DailyDigest
from agents2.profile import MY_PROFILE

# --- Configuration ---
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

# --- Modern Newsletter CSS ---
EMAIL_CSS = """
<style>
    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; background-color: #f9f9f9; padding: 20px; }
    .header { text-align: center; padding: 20px 0; border-bottom: 3px solid #2c3e50; }
    .header h1 { margin: 0; color: #2c3e50; font-size: 24px; }
    .date { color: #7f8c8d; font-size: 14px; margin-top: 5px; }
    .article-card { background: #ffffff; padding: 20px; margin: 20px 0; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #eee; }
    .score-badge { background-color: #e67e22; color: white; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: bold; text-transform: uppercase; }
    .article-title { margin: 10px 0; font-size: 18px; color: #2980b9; text-decoration: none; display: block; }
    .article-title:hover { text-decoration: underline; }
    .summary-text { color: #444; font-size: 15px; margin-bottom: 15px; }
    .ai-insight { background: #f0f7fb; border-left: 4px solid #3498db; padding: 10px; font-size: 13px; color: #2c3e50; font-style: italic; }
    .footer { text-align: center; padding: 20px; font-size: 12px; color: #bdc3c7; border-top: 1px solid #eee; margin-top: 30px; }
    .btn { display: inline-block; background: #3498db; color: white; padding: 10px 20px; border-radius: 5px; text-decoration: none; font-size: 14px; margin-top: 10px; }
</style>
"""

class EmailAgent:
    def __init__(self):
        self.sender_email = os.getenv("EMAIL_SENDER")
        self.password = os.getenv("EMAIL_PASSWORD")
        self.recipient_email = os.getenv("EMAIL_RECIPIENT")
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", 465))

    def generate_digest_html(self):
        """Fetches top scored articles and generates the newsletter HTML."""
        session = SessionLocal()
        
        # 1. Fetch top 8 articles with impact_score >= 50
        articles = session.query(AggregatedSummary)\
            .filter(AggregatedSummary.impact_score >= 50)\
            .order_by(AggregatedSummary.impact_score.desc())\
            .limit(8).all()
        
        if not articles:
            logger.warning("⚠️ No high-score articles found for today's digest.")
            session.close()
            return None

        # 2. Build the Article Cards
        article_html_blocks = ""
        for art in articles:
            article_html_blocks += f"""
            <div class="article-card">
                <span class="score-badge">Impact: {art.impact_score}/100</span>
                <a href="{art.source_link}" class="article-title">{art.article_name}</a>
                <p class="summary-text">{art.summary}</p>
                <div class="ai-insight">
                    <strong>AI Insight:</strong> {art.relevance_explanation}
                </div>
                <a href="{art.source_link}" class="btn">Read Original</a>
            </div>
            """

        # 3. Combine into final template
        today_str = date.today().strftime("%B %d, %Y")
        final_html = f"""
        <html>
        <head>{EMAIL_CSS}</head>
        <body>
            <div class="header">
                <h1>Personal AI Digest for {MY_PROFILE.name}</h1>
                <div class="date">{today_str}</div>
            </div>
            {article_html_blocks}
            <div class="footer">
                You're receiving this because your AI Agents found news matching your interest in 
                <strong>{", ".join(MY_PROFILE.interests[:3])}</strong>.<br>
                Generated by Agents2 Pipeline 🤖
            </div>
        </body>
        </html>
        """
        
        # --- 4. FIX: Upsert Logic (Check if today's entry exists) ---
        existing_digest = session.query(DailyDigest).filter(
            func.date(DailyDigest.date) == date.today()
        ).first()

        if existing_digest:
            logger.info(f"🔄 Updating existing digest record for {date.today()}")
            existing_digest.title = f"AI Digest: {today_str}"
            existing_digest.content = final_html
        else:
            logger.info(f"🆕 Creating new digest record for {date.today()}")
            new_digest = DailyDigest(
                title=f"AI Digest: {today_str}",
                content=final_html
            )
            session.add(new_digest)

        try:
            session.commit()
            logger.info("✅ Database record synchronized.")
        except Exception as e:
            session.rollback()
            logger.error(f"❌ Failed to save to database: {e}")
            return None
        finally:
            session.close()
        
        return final_html

    def send_email(self, html_content):
        """Sends the compiled newsletter via SMTP."""
        if not self.sender_email or not self.password:
            logger.error("❌ Email credentials missing in .env")
            return

        try:
            message = MIMEMultipart("alternative")
            message["Subject"] = f"🚀 Your AI News Digest - {date.today().strftime('%d %b')}"
            message["From"] = f"AI News Agent <{self.sender_email}>"
            message["To"] = self.recipient_email

            message.attach(MIMEText(html_content, "html"))

            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(self.smtp_server, self.smtp_port, context=context) as server:
                server.login(self.sender_email, self.password)
                server.sendmail(self.sender_email, self.recipient_email, message.as_string())

            logger.info(f"✅ Email sent successfully to {self.recipient_email}")

        except Exception as e:
            logger.error(f"❌ Failed to send email: {e}")

    def run(self):
        logger.info("📧 Starting Email Agent...")
        html_report = self.generate_digest_html()
        
        if html_report:
            self.send_email(html_report)
        else:
            logger.info("⏭️ Skipping email: No relevant articles to report.")

if __name__ == "__main__":
    EmailAgent().run()